version: 2
jobs:
  build:
    working_directory: ~/alpaca-image-generator-angular
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - restore_cache:
          key: alpaca-image-generator-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: alpaca-image-generator-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm install -g @angular/cli
      - run: ng test --wach=false --browsers=ChromeHeadlessCI
